#! /bin/bash

# Script Arguments
readonly ARGS="$*"
readonly ARGA=("$@")

readonly RUNNING_AS="${SUDO_USER:-$USER}";
readonly RUNNING_AS_HOME="$(/bin/find /home/{,nexcess.net/}"${RUNNING_AS}" -mindepth 0 -maxdepth 0 -type d 2> /dev/null)"

# Configurable Variables
readonly TMP_EXT=".nexcess.bak"
OUTPUT_DIR="${RUNNING_AS_HOME}/nex_strace"
readonly TEMP_DIR="/dev/shm"
readonly PIPE_PREFIX="${TEMP_DIR}/nexcess_strace_pipe-"
readonly DEFAULT_IP="${MY_IP:-192.240.191.2}"
readonly STRACE_FLAGS="-fTrvs200000"

# Alias executables to prevent PATH issues
readonly CAT='/bin/cat'
readonly CHMOD='/bin/chmod'
readonly CHOWN='/bin/chown'
readonly CP='/bin/cp'
readonly DATE='/bin/date'
readonly DD='/bin/dd'
readonly FIND='/bin/find'
readonly GREP='/bin/grep'
readonly GZIP='/bin/gzip'
readonly KILL='/bin/kill'
readonly MKDIR='/bin/mkdir'
readonly MKFIFO='/usr/bin/mkfifo'
readonly MV='/bin/mv'
readonly PKILL='/usr/bin/pkill'
readonly RM='/bin/rm'
readonly SLEEP='/bin/sleep'
readonly STRACE='/usr/bin/strace'
readonly TAIL='/usr/bin/tail'
readonly TR='/usr/bin/tr'

# Necessary Global Variables
MONITOR_PID=""
PIPE_NAME=""
REMOVE_PIPE=""
FILES=()
FILES_USED=()
CLI_RUN=""


# Print usage
_usage() {

  "$CAT" <<- EOF

  Strace wrapper aimed at simplifying strace capturing for php requests. Captures
  strace and php GLOBALS variable information of matching requests to a website and
  outputs data to $OUTPUT_DIR. It can be safely run on each node of a cluster without
  conflict. Unless overriden with the -i flag, this will only capture requests from
  the Nexcess office IP. For remote employees, the value of \$MY_IP environment variable,
  if you have it set, will also override this.

  Simplest invocation from docroot:

    capstrace index.php

  In this form, no other arguments should be used and there is no filtering of requests aside
  from the IP filtering described above.

  Advanced usage example:

    capstrace -f index.php,admin/index.php -i all -u api/soapy -q run=5 -d 6

  This monitors requests hitting either index.php or admin/index.php. Due to the usage of
  -i all means that it will capture matching requests from any IP. Due to the -u and -q flags,
  this will only capture requests with "api/soapy" in the request URI, and with a query string
  matching "run=5". This will also run as a background process to capture all matching requests
  for the next 6 hours by usage of the -d flag. If you wish to stop this prematurely, capstrace -k
  will stop the background process.

  Usage:

  capstrace [options]

  -h|--help                        Prints this message.

  -f|--file FILE                   Target file for catching process.
                                   Usually an index.php, but not always.
                                   Accepts a comma separated list of files
                                   for capturing processes at multiple entry
                                   points.

  -i|--ip-address REMOTE_ADDR,all  IP address initiating process.
                                   Default value is Nexcess IP: 192.240.191.2
                                   or the value of \$MY_IP if it is set in your
                                   environment. Special value of 'all' will
                                   match any IP.

  -u|--uri REQUEST_URI             Specific URI to monitor for.

  -q|--query-string QUERY_STRING   Specific query string to monitor for.

  -d|--daemonize  HOURS_TO_RUN     Runs program as a daemon for the number of
                                   hours specified.

  -k|--kill                        Manually kill daemonized capstrace instance.

  -c|--cli                         Ignore file extensions and request filtering
                                   to allow for easy strace capture of cli scripts.


  -o|--output DIRECTORY            Manually specify an output directory.

EOF

}

# Convert long command line options into short ones for getopts
_cmdline() {

  local x;

  for x in ${ARGA[*]}; do

    local args

    case "$x" in
      "--help"|"-h")
        args="${args}-h "
        ;;
      "--file"|"-f")
        args="${args}-f "
        ;;
      "--ip-address"|"-i")
        args="${args}-i "
        ;;
      "--query-string"|"-q")
        args="${args}-q "
        ;;
      "--uri"|"-u")
        args="${args}-u "
        ;;
      "--daemonize"|"-d")
        args="${args}-d "
        ;;
      "--kill"|"-k")
        args="${args}-k "
        ;;
      "--cli"|"-c")
        args="${args}-c "
        ;;
      "--output"|"-o")
        args="${args}-o "
        ;;
      *)
        args="${args}${x} ";
        ;;
    esac

  done

  echo "$args";

}

# Insert code into target file
_addCode () {

  local file address address_string uri uri_string query query_string;

  file="$1";
  address="$2";
  uri="$3";
  query="$4"

  "$MV" "$file"{,"$TMP_EXT"} || return 1;

  "$CP" -a "$file""$TMP_EXT" "$file";

  if [[ -z "$CLI_RUN" ]]; then
    if [[ "$uri" == "NULL" ]]; then
      uri_string="";
    else
      uri_string=" and (strlen(strstr(\$_SERVER[\"REQUEST_URI\"],\"$uri\"))>0)";
    fi

    if [[ "$query" == "NULL" ]]; then
      query_string="";
    else
      query_string=" and (strlen(strstr(\$_SERVER[\"QUERY_STRING\"],\"$query\"))>0)";
    fi

    if [[ "$address" == "all" ]]; then
      address_string="1";
    else
      address_string="\$_SERVER[\"REMOTE_ADDR\"] == \"$address\" || (strlen(strstr(\$_SERVER[\"HTTP_X_FORWARDED_FOR\"],\"$address\"))>0)";
    fi
  else
    address_string="1";
  fi

  "$CAT" << EOF > "$file"
<?php
  if((@($address_string)$uri_string)$query_string){

    file_put_contents("$PIPE_NAME",getmypid() . "\n");
    usleep(100000);
    file_put_contents("$TEMP_DIR/" . date('Y-m-d-H:i:s') . "-" . getmypid() . "-GLOBALS", print_r(\$GLOBALS,true) . "\\n\\n" . file_get_contents("php://input"));
  }
?>
EOF

"$CAT" "$file""$TMP_EXT" >> "$file";

}

# Perform "$STRACE" of request
_strace () {

  local output pid str_pid daemon_time

  pid="$1";
  daemon_time="$2";

  output="${OUTPUT_DIR}/$("$DATE" "+%F-%T")-$pid-strace";

  if [[ -n "$daemon_time" ]]; then
    "$STRACE" "$STRACE_FLAGS" -o "$output" -p"$pid" &> /dev/null &
  else
    "$STRACE" "$STRACE_FLAGS" -o "$output" -p"$pid" &
  fi

  str_pid="$!"

  trap 'break' INT QUIT TERM;
  "$SLEEP" 0.1;

  # Kill strace once php process becomes idle
  while [[ -e /proc/"$str_pid" ]]; do

    if "$TAIL" | "$GREP" -qE "^$pid .*(accept\([0-9]|\+\+\+ (killed|exited))"; then

      "$KILL" "$str_pid" 2>/dev/null || echo "$pid exited";
      break;

    fi

  done < "$output"

  "$KILL" "$str_pid" 2> /dev/null;

  "$FIND" "${TEMP_DIR}/" -name "*-GLOBALS" -user "$(pwd | "$GREP" -Po "((/chroot)?/home|/local)/\K[^/]*")" -exec "$MV" -t "$OUTPUT_DIR" {} + 2>/dev/null

  if [[ "$daemon_time" ]]; then
    "$GZIP" "$output";
  fi

  "$CHMOD" 600 "${OUTPUT_DIR}"/*
  "$CHOWN" "${RUNNING_AS}." "${OUTPUT_DIR}"/*

}

# Monitor for incoming requests
_monitor () {

  local pid daemon_time start_time current_time

  daemon_time="$1";

  # Perform monitoring in background
  (while (true); do

    read -r pid;

    if [[ -n $pid ]]; then
      _strace "$pid" "$daemon_time" &
    fi

  done <"$PIPE_NAME";) &


  MONITOR_PID="$!"

  trap 'return' INT QUIT TERM;

  if [[ $daemon_time ]]; then

    start_time="$("$DATE" "+%s")"

    while [[ -e /proc/"$MONITOR_PID" ]]; do

      current_time="$("$DATE" "+%s")"

      if (( current_time > (start_time + daemon_time) )) ; then
        return;
      fi

      "$SLEEP" 5;

    done
  else

    # Handle user exiting capstrace

    printf "Waiting for process. Press enter to stop.\n";

    read -r;

  fi

}

# Perform setup tasks
_setup() {

  local x address uri query

  address="$1"
  uri="$2"
  query="$3"

  # Create output directory if necessary and restrict perms
  [[ -d $OUTPUT_DIR ]] || "$MKDIR" -p "${OUTPUT_DIR}";
  "$CHMOD" 700 "${OUTPUT_DIR}"
  "$CHOWN" "${RUNNING_AS}." "${OUTPUT_DIR}"

  # Add the needed code to any files that don't currently have it
  for x in ${FILES[*]}; do

    if [[ ! -f "$x" ]]; then
      echo "$x is not a regular file, skipping.";
      continue;
    fi

    if [[ -z "${CLI_RUN}" && ! "$x" == *.php ]]; then
      echo "$x missing .php extension, skipping.";
      continue;
    fi

    if [[ -z "$PIPE_NAME" ]]; then
      # Check if we already have a pipe id in the file ( Mainly for clusters )
      PIPE_NAME=$("$GREP" -Po "${PIPE_PREFIX}[^\"]*" "${x}") \
        || PIPE_NAME="${PIPE_PREFIX}$(uuidgen)"
    fi

    if ! "$GREP" -Fq "${PIPE_NAME}" "$x"; then
      _addCode "$x" "${address}" "${uri}" "${query}" \
        && FILES_USED+=("$x");
    fi

  done

  if [[ -z ${FILES_USED[0]} ]]; then
    echo "No files modified."
  fi

  # Create pipe if not already present
  if [[ ! -e "$PIPE_NAME" ]]; then
    "$MKFIFO" -m 666 "$PIPE_NAME";
    REMOVE_PIPE="yes";
  fi

}

# Clean up any changes made
_cleanUp() {

  local x
  # Clean up the stuff we touched
  for x in ${FILES_USED[*]}; do

    if [[ -f "$x" && -e "${x}${TMP_EXT}" ]]; then
      "$MV" -f "$x"{"$TMP_EXT",}
    fi

  done

  # Flush pipe to prevent any remaining PHP processes from hanging
  if [[ "$REMOVE_PIPE" == "yes" ]]; then
    "$SLEEP" 0.1;
    "$DD" if="$PIPE_NAME" iflag=nonblock of=/dev/null &> /dev/null
    "$RM" -f "$PIPE_NAME";
  fi

  "$KILL" "$MONITOR_PID" 2> /dev/null

}

# Main
main () {

  local address uri query daemon_time x;

  # Parse command line options
  while getopts "hf:i:u:q:d:kco:" OPTION $(_cmdline); do

    case $OPTION in
      h)
        _usage;
        exit 0;
        ;;
      f)
        mapfile -t FILES < <(echo "$OPTARG" | "$TR" ',' '\n' );

        for x in ${FILES[*]}; do

          if [[ ! -e "$x" ]]; then

            echo "$x is not a valid filename";
            return 1;

          fi
        done
        ;;
      i)
        address="$OPTARG";
        ;;
      u)
        uri="$OPTARG";
        ;;
      q)
        query="$OPTARG";
        ;;
      d)
        if [[ "$OPTARG" == [0-9]* ]]; then
          daemon_time="$(( $(echo "$OPTARG" | "$GREP" -Po '\d*') * 3600 ))";
        else
          echo "Invalid daemon time.";
          exit 4;
        fi
        ;;
      k)
        "$PKILL" capstrace -P 1
        exit;
        ;;
      c)
        CLI_RUN="true";
        ;;
      o)
        OUTPUT_DIR="$OPTARG"
        ;;
      *);;
    esac

  done

  # Set defaults where necessary
  if [[ -z "${FILES[0]}" ]]; then
    if [[ -e "${ARGA[0]}" ]]; then
      FILES=("${ARGA[0]}");
    else
      _usage;
      return 1;
    fi
  fi

  trap "_cleanUp" EXIT;

  _setup "${address:=$DEFAULT_IP}" "${uri:=NULL}" "${query:=NULL}";

  _monitor "$daemon_time";

  _cleanUp;

}

# Background script if run in daemon mode
if echo "$ARGS" | "$GREP" -Pq '\s*(-d|--daemonize) \d*'; then
  main &
else
  main;
fi
