# vim:ft=bash
typeset -g     P9K_NODE_VERSION_PROJECT_ONLY=false
typeset -g     POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=false
typeset -g     POWERLEVEL9K_ALWAYS_SHOW_USER=false
typeset -g     POWERLEVEL9K_ANACONDA_LEFT_DELIMITER="("
typeset -g     POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=")"
typeset -g     POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=false
typeset -g     POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
typeset -g -i  POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD=999
typeset -g -a  POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND
typeset -g -i  POWERLEVEL9K_BATTERY_LOW_THRESHOLD=10
typeset -g     POWERLEVEL9K_BATTERY_VERBOSE=true
typeset -g     POWERLEVEL9K_CHRUBY_SHOW_ENGINE=true
typeset -g     POWERLEVEL9K_CHRUBY_SHOW_VERSION=true
typeset -g     POWERLEVEL9K_COLOR_SCHEME="dark"
typeset -g -i  POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
typeset -g -i  POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset -g     POWERLEVEL9K_CONTEXT_TEMPLATE="%n@%m"
typeset -g     POWERLEVEL9K_DATE_FORMAT="%D{%d.%m.%y}"
typeset -g     POWERLEVEL9K_DIR_MAX_LENGTH=0
typeset -g     POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=false
typeset -g -a  POWERLEVEL9K_DIR_PACKAGE_FILES
POWERLEVEL9K_DIR_PACKAGE_FILES=(package.json composer.json)
typeset -g     POWERLEVEL9K_DIR_PATH_ABSOLUTE=false
typeset -g     POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=false
typeset -g     POWERLEVEL9K_DIR_PATH_SEPARATOR="/"
typeset -g     POWERLEVEL9K_DIR_PATH_SEPARATOR_FOREGROUND=""
typeset -g     POWERLEVEL9K_DIR_SHOW_WRITABLE=false
typeset -g     POWERLEVEL9K_DISABLE_GITSTATUS=false
typeset -g     POWERLEVEL9K_DISABLE_RPROMPT=false
typeset -g -i  POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL=95
typeset -g     POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=false
typeset -g -i  POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=90
typeset -g     POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME=false
typeset -g     POWERLEVEL9K_HIDE_BRANCH_ICON=false
typeset -g     POWERLEVEL9K_HOME_FOLDER_ABBREVIATION="~"
typeset -g     POWERLEVEL9K_HOST_TEMPLATE="%m"
typeset -g     POWERLEVEL9K_IGNORE_TERM_COLORS=false
typeset -g     POWERLEVEL9K_IGNORE_TERM_LANG=false
typeset -g     POWERLEVEL9K_IP_INTERFACE="^[^                                                                ]+"
typeset -g     POWERLEVEL9K_JAVA_VERSION_FULL=true
typeset -g -a  POWERLEVEL9K_KUBECONTEXT_CLASSES
typeset -g     POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE=true
typeset -g -a  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
typeset -g -i  POWERLEVEL9K_LOAD_WHICH=5
typeset -g -i  POWERLEVEL9K_MAX_CACHE_SIZE=10000
typeset -g     POWERLEVEL9K_MODE=""
typeset -g     POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset -g     POWERLEVEL9K_PROMPT_ON_NEWLINE=false
typeset -g     POWERLEVEL9K_PUBLIC_IP_HOST="http://ident.me"
typeset -g -a  POWERLEVEL9K_PUBLIC_IP_METHODS
POWERLEVEL9K_PUBLIC_IP_METHODS=(dig curl wget)
typeset -g     POWERLEVEL9K_PUBLIC_IP_NONE=""
typeset -g -i  POWERLEVEL9K_PUBLIC_IP_TIMEOUT=300
typeset -g     POWERLEVEL9K_PUBLIC_IP_VPN_INTERFACE=""
typeset -g     POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
typeset -g     POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false
typeset -g -a  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)
typeset -g     POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
typeset -g     POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(.shorten_folder_marker|.bzr|CVS|.git|.hg|.svn|.terraform|.citc)"
typeset -g     POWERLEVEL9K_SHORTEN_STRATEGY=""
typeset -g     POWERLEVEL9K_SHOW_CHANGESET=false
typeset -g     POWERLEVEL9K_SHOW_RULER=false
typeset -g     POWERLEVEL9K_STATUS_CROSS=false
typeset -g     POWERLEVEL9K_STATUS_HIDE_SIGNAME=false
typeset -g     POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=false
typeset -g     POWERLEVEL9K_STATUS_OK=true
typeset -g     POWERLEVEL9K_STATUS_SHOW_PIPESTATUS=true
typeset -g     POWERLEVEL9K_STATUS_VERBOSE=true
typeset -g     POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S}"
typeset -g     POWERLEVEL9K_USER_TEMPLATE="%n"
typeset -g     POWERLEVEL9K_VCS_ACTIONFORMAT_FOREGROUND=red
typeset -g -a  POWERLEVEL9K_VCS_BACKENDS
POWERLEVEL9K_VCS_BACKENDS=(git)
typeset -g -i  POWERLEVEL9K_VCS_COMMITS_AHEAD_MAX_NUM=-1
typeset -g -i  POWERLEVEL9K_VCS_COMMITS_BEHIND_MAX_NUM=-1
typeset -g -a  POWERLEVEL9K_VCS_GIT_HOOKS
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)
typeset -g -a  POWERLEVEL9K_VCS_HG_HOOKS
POWERLEVEL9K_VCS_HG_HOOKS=(vcs-detect-changes)
typeset -g     POWERLEVEL9K_VCS_HIDE_TAGS=false
typeset -g -i  POWERLEVEL9K_VCS_INTERNAL_HASH_LENGTH=8
typeset -g     POWERLEVEL9K_VCS_LOADING_TEXT=loading
typeset -g -i  POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
typeset -g -F  POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0.05
typeset -g     POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=false
typeset -g -i  POWERLEVEL9K_VCS_STAGED_MAX_NUM=1
typeset -g -a  POWERLEVEL9K_VCS_SVN_HOOKS
POWERLEVEL9K_VCS_SVN_HOOKS=(vcs-detect-changes  svn-detect-changes)
typeset -g -i  POWERLEVEL9K_VCS_UNSTAGED_MAX_NUM=1
typeset -g -i  POWERLEVEL9K_VCS_UNTRACKED_MAX_NUM=1
typeset -g     POWERLEVEL9K_VI_COMMAND_MODE_STRING="NORMAL"
typeset -g     POWERLEVEL9K_VI_INSERT_MODE_STRING="INSERT"
typeset -g     POWERLEVEL9K_VPN_IP_INTERFACE="tun"
typeset -g     POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=" "
typeset -g     POWERLEVEL9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS=" "

#typeset -g     POWERLEVEL9K_BATTERY_STAGES
#typeset -g     POWERLEVEL9K_CHANGESET_HASH_LENGTH
#typeset -g     POWERLEVEL9K_DIR_PATH_HIGHLIGHT_FOREGROUND
#typeset -g     POWERLEVEL9K_GITSTATUS_DIR
#typeset -g     POWERLEVEL9K_KUBECONTEXT_BACKGROUND
#typeset -g     POWERLEVEL9K_KUBECONTEXT_CLASSES
#typeset -g     POWERLEVEL9K_KUBECONTEXT_FOREGROUND
#typeset -g     POWERLEVEL9K_KUBECONTEXT_OTHER_BACKGROUND
#typeset -g     POWERLEVEL9K_KUBECONTEXT_PROD_BACKGROUND
#typeset -g     POWERLEVEL9K_KUBECONTEXT_TESTING_BACKGROUND
#typeset -g     POWERLEVEL9K_PROMPT_ADD_NEWLINE_COUNT
#typeset -g     POWERLEVEL9K_RULER_CHAR
#typeset -g     POWERLEVEL9K_SHORTEN_DELIMITER
#typeset -g     POWERLEVEL9K_SHORTEN_DELIMITER_LENGTH
#typeset -g     POWERLEVEL9K_SHORTEN_DIR_LENGTH
#typeset -g     POWERLEVEL9K_VCS_MAX_NUM_STAGED
#typeset -g     POWERLEVEL9K_VCS_MAX_NUM_UNSTAGED
#typeset -g     POWERLEVEL9K_VCS_MAX_NUM_UNTRACKED
#typeset -g     POWERLEVEL9K_VCS_SHORTEN_DELIMITER
#typeset -g     POWERLEVEL9K_VCS_SHORTEN_LENGTH=""
#typeset -g     POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=""
## POWERLEVEL9K_VCS_SHORTEN_STRATEGY truncate_middle or truncate_from_right
#typeset -g     POWERLEVEL9K_VCS_SHORTEN_STRATEGY=""
#typeset -g     POWERLEVEL9K_VI_VISUAL_MODE_STRING=""
