#! /bin/bash

# Script Arguments
readonly ARGS="$*"
readonly ARGA=("$@")

# Configurable Variables
CONFIG_DIR="${HOME}/.config/lutris/games/"
LUTRIS_DB="${HOME}/.local/share/lutris/pga.db"

# Alias executables to prevent PATH issues

# Necessary Global Variables
PLATFORM=""
RUNNER=""
DIRECTORY=""
NAME=""
SLUG=""
INSTALLED=""
INSTALLED_AT=""
CONFIGPATH=""

# Print usage
_usage() {

  cat <<- EOF
  This is the usage
EOF

}

# Convert long command line options into short ones for getopts
_cmdline() {

  local x;

  for x in ${ARGA[*]}; do

    case "$x" in
      "--help"|"-h")
        args="${args}-h "
        ;;
      *)
        args="${args}${x} "
        ;;
    esac
  done

  echo "$args";

}

# Filter name
_filterName() {

  sed \
    -e "s/'//g" \
    -e 's/\....$//' \
    -e 's/([^\)]*)//g' \
    -e 's/\[[^]]*]//g' \
    -e 's/\(.*\), *\(The\)/\2 \1/' \
    | tr '_' ' '

}

# Filter slug
_filterSlug() {

  sed -e 's/ *$//' -e 's/-+/-/g' \
    | tr '[:upper:]' '[:lower:]' \
    | tr '_ ' '-' \
    | sed -e 's/--*/-/g'

}

# Help user select an EXE file (dosbox)
_selectExe() {

  executables=($(find "${DIRECTORY}/GAME" -iname "*.exe" ))

  for (( i=0; i<${#executables[@]}; i++ )); do

    echo "$i  ${executables[$i]}";

  done | column -t;

  echo;
  read -rep "Choose main_file:" selection;

}

# dosbox config
_dosboxConfig() {

  RUNNER="dosbox"

  cat <<- EOF > "${CONFIG_DIR}${CONFIGPATH}.yml"
${RUNNER}: {}
game:
  config_file: ${DIRECTORY}/dosbox.conf
  main_file: ${executables[selection]}
  working_dir: ${DIRECTORY}
system: {}
EOF

}

# gamecube config
_gamecubeConfig() {

  PLATFORM="Nintendo Gamecube"
  RUNNER="dolphin"

  cat <<- EOF > "${CONFIG_DIR}${CONFIGPATH}.yml"
${RUNNER}: {}
game:
  main_file: $1
  platform: '0'
system: {}
EOF

}

# wii config
_wiiConfig() {

  PLATFORM="Nintendo Wii"
  RUNNER="dolphin"

  cat <<- EOF > "${CONFIG_DIR}${CONFIGPATH}.yml"
${RUNNER}: {}
game:
  main_file: $1
  platform: '1'
system: {}
EOF

}

# Main
main () {

  while getopts "h" OPTION $(_cmdline); do

    case $OPTION in
      h)
        _usage;
        exit 0;
        ;;
      *);;
    esac
  done

  for game in "${game_list[@]}"; do

    NAME="$(echo ${1##*/} | _filterName)"
    SLUG="$(echo "$NAME" | _filterSlug)"

    INSTALLED=1
    INSTALLED_AT="$(date '+%s')"
    CONFIGPATH="${SLUG}-${INSTALLED_AT}"

    sqlite3 "${LUTRIS_DB}" <<-EOF || exit 1
  INSERT INTO Games
  (name,slug,platform,runner,directory,installed,installed_at,configpath)
  VALUES
  ('$NAME','$SLUG','$PLATFORM','$RUNNER','$DIRECTORY','$INSTALLED','$INSTALLED_AT','$CONFIGPATH');
EOF

  done

}

main;
