#! /bin/zsh

[ -r "${HOME}/.iterm2_shell_integration.zsh" ] \
  && source "${HOME}/.iterm2_shell_integration.zsh"

readonly SED='/usr/local/bin/sed'
readonly GREP='/usr/local/bin/grep'
readonly FIND='/usr/local/bin/find'
readonly READLINK='/usr/bin/readlink'

[ -r "${HOME}/.zsh/main.zsh" ] \
  && source "${HOME}/.zsh/main.zsh";

alias rm='rm -r'
unalias chown;
unalias chmod;

export PATH="$PATH:${HOME}/.local/bin"

export nex_user_shell="zsh";

update_brew () {

  brew update;
  brew upgrade;
  brew cleanup;

	for f in $(find /usr/local/Cellar/*/*/bin/*); do

		bin="${f##*/}";

		if [[ -e /usr/local/bin/${bin} ]]; then
			rm -f "/usr/local/bin/${bin}";
		fi

		ln -s "$f" "/usr/local/bin/${bin}";

	done

	for f in $(find /usr/local/Cellar/{grep,gnu-sed,gawk,coreutils}/*/bin/g*); do

		bin="${f##*/g}";

		if [[ -e "/usr/local/bin/${bin}" ]]; then
			rm -f "/usr/local/bin/${bin}";
		fi

		ln -s "$f" "/usr/local/bin/${bin}";

	done
}
