#! /bin/zsh

#[ -r "${HOME}/.iterm2_shell_integration.zsh" ] \
  #&& source "${HOME}/.iterm2_shell_integration.zsh"

readonly SED='/usr/local/bin/sed'
readonly GREP='/usr/local/bin/grep'
readonly FIND='/usr/local/bin/find'
readonly READLINK='/usr/bin/readlink'

export TERM="screen-256color"

[ -r "${HOME}/.zsh/env.zsh" ] \
  && source "${HOME}/.zsh/env.zsh";
[ -r "${HOME}/.zsh/alias.zsh" ] \
  && source "${HOME}/.zsh/alias.zsh";
[ -r "${HOME}/.zsh/plugins_core.zsh" ] \
  && source "${HOME}/.zsh/plugins_core.zsh";

#[ -r "${HOME}/.zsh/main.zsh" ] \
  #&& source "${HOME}/.zsh/main.zsh";

alias rm='rm -r'

export PATH="$PATH:${HOME}/.local/bin"

export nex_user_shell="zsh";

update_brew () {

  brew update;
  brew upgrade;
  brew cleanup;

	for f in $(find /usr/local/Cellar/*/*/bin/*); do

		bin="${f##*/}";

		if [[ -e /usr/local/bin/${bin} ]]; then
			rm -f "/usr/local/bin/${bin}";
		fi

		ln -s "$f" "/usr/local/bin/${bin}";

	done

	for f in $(find /usr/local/Cellar/{grep,gnu-sed,gawk,coreutils}/*/bin/g*); do

		bin="${f##*/g}";

		if [[ -e "/usr/local/bin/${bin}" ]]; then
			rm -f "/usr/local/bin/${bin}";
		fi

		ln -s "$f" "/usr/local/bin/${bin}";

	done
}

if [[ ! -e "${HOME}/.zplugin/bin/zplugin.zsh" ]]; then
  rm -r "${HOME}/.zplugin" 2> /dev/null
  mkdir "${HOME}/.zplugin"
  git clone https://github.com/zdharma/zplugin.git ~/.zplugin/bin
fi
