#! /bin/zsh

# Load dependencies.
pmodload 'helper'

prompt_matt_precmd() {

  setopt LOCAL_OPTIONS
  unsetopt XTRACE KSH_ARRAYS

  if [[ -x /usr/bin/quota ]] && ((( OS_VERSION < 7 )) || [[ $USER == "${HOME/*\//}" ]]); then
    _quota=$(quota -qg $(pwd | grep -Po "/home/\K[^/]*") 2> /dev/null | grep -Po "Over|grace|limit")
  fi

}

run_prompt_game (){

  red="%F{1}"
  green="%F{10}"
  yellow="%F{11}"
  grape="%F{92}"
  strawberry="%F{9}"
  mellon="%F{162}"
  reset="%F{7}"

  symbol[1]="$red🍒$reset"
  symbol[2]="$green🍏$reset"
  symbol[3]="$strawberry🍓$reset"
  symbol[4]="$grape🍇$reset"
  symbol[5]="$mellon🍉$reset"

  n1=$((RANDOM%5 + 1))
  n2=$((RANDOM%5 + 1))
  n3=$((RANDOM%5 + 1))

  win=0
  winst=""

  if (((n1==n2) || (n1==n3) || (n2==n3))); then
    win=10;
    winst=" $yellow⭐$reset"
  fi

  if (((n1==n2) && (n1==n3))); then
    win=$((100*(n1)));
    winst=" $yellow🌟 $win 🌟$reset"
  fi

  PROMPT_GAME_CASH=$((PROMPT_GAME_CASH+win-10))
  PROMPT_GAME_TEXT="$(tput bold)[${symbol[n1]}|$(tput bold)${symbol[n2]}|$(tput bold)${symbol[n3]}]$winst $green💵$reset:$yellow$PROMPT_GAME_CASH$reset "
}
PROMPT_GAME_CASH=1000

prompt_matt_setup() {

  setopt LOCAL_OPTIONS
  unsetopt XTRACE KSH_ARRAYS

  OS_VERSION=$(grep -Po 'release \K\d' /etc/centos-release 2> /dev/null);

  prompt_opts=(cr percent sp subst)

  # Load required functions.
  autoload -Uz add-zsh-hook

  # Add hook for calling git-info before each command.
  add-zsh-hook precmd prompt_matt_precmd

	if [[ -n "${DO_PROMPT_GAME}" ]]; then
    PROMPT_GAME_CASH=1000;
    add-zsh-hook precmd run_prompt_game
  fi

  # Set editor-info parameters.
  zstyle ':prezto:module:editor:info:completing' format '%B%F{7}...%f%b'
  zstyle ':prezto:module:editor:info:keymap:primary' format ' %B%F{1}❯%F{3}❯%F{2}❯%f%b'
  zstyle ':prezto:module:editor:info:keymap:primary:overwrite' format ' %F{3}♺%f'
  zstyle ':prezto:module:editor:info:keymap:alternate' format ' %B%F{2}❮%F{3}❮%F{1}❮%f%b'

  # Set up non-zero return value display
  local show_return="✘ "

  # Default is to show the return value
  if zstyle -T ':prezto:module:prompt' show-return-val; then
    show_return+='%? '
  fi

  _quota=""

  # Define prompts.
  PROMPT='${PROMPT_GAME_TEXT}%B${SSH_TTY:+"%F{3}%m%f "}%F{4}%~%(!. %B%F{1}#%f%b.)${editor_info[keymap]} '
  RPROMPT='${editor_info[overwrite]}'
  RPROMPT+='%F{9}${_quota}%f'
  RPROMPT+='%(?:: %F{1}'${show_return}'%f)'
  SPROMPT='zsh: correct %F{1}%R%f to %F{2}%r%f [nyae]? '

}

prompt_matt_setup "$@"
